### ISSUE TITLE
MB will not compile in Windows

### ISSUE THREAD

**Issue by paulwrightwork** [WTCN-computational-anatomy-group/diffeo-segment#2]
I have tried following the instructions in https://en.wikibooks.org/wiki/SPM/SPM12_MEX_Compilation_on_Windows and installing MinGW as a MATLAB add-on. Either way, I get the following:
```
>> mex -O -largeArrayDims -DSPM_WIN32 spm_gmmlib.c gmmlib.c
Building with 'MinGW64 Compiler (C)'.
Error using mex
'path\to\spm_gmmlib.mexw64' is not a MEX file. For more information, see File is not a MEX file.
```

**Comment by gllmflndn** [comment]
Could you try and check with this precompiled MEX file: https://github.com/spm/spm/blob/main/spm_gmmlib.mexw64 ?
